### ISSUE TITLE
Set the client timezone to Asia/Seoul explicitly

### ISSUE THREAD

**Issue by jhaemin** [payw-org/eodiro#268]
If eodiro respects to each client's timezone, the Vacant service could not calculate the time correctly.

**Comment by 97e57e** [comment]
How about use server's time for sync all clients?

**Comment by jhaemin** [comment]
@97e57e 
To make sure, all the data fetched from the server are indeed synced with the same timezone which is `Asia/Seoul`.
But most of the time calculations are processed on the client side and few of them are planned to feature live updates. If a client depends on the server's time, it has to fetch the time from server everytime it should recalculate, somewhat unnecessarily additional network overhead.
Anyway, thanks for replying with a great idea. You're solution works perfectly from a point of view of single source of truth. At this time, setting the client side timezone is fairly much proper way to solve the problem.

**Comment by 97e57e** [comment]
@jhaemin
Thank you for your kindly reply!
but, i have a question
if client use their timezone, users can not change the client's time themselves?

**Comment by jhaemin** [comment]
@97e57e 
Of course they can't. Actually they wouldn't have to, since Chung-Ang university is placed in Seoul.
