### ISSUE TITLE
Body editor is invisible on Firefox 76.0.1

### ISSUE THREAD

**Issue by LiteHell** [payw-org/eodiro#275]
I'm using Firefox 76.0.1 64bit and Windows 10 Build 18363.
Content editor is invisible on Firefox when writing new articles. Nothing, including placeholder, is visible even i tried to type something.(See screenshot below)
![image](https://user-images.githubusercontent.com/12497886/83331934-97fd9900-a2d3-11ea-80c4-6a698bc6c633.png)
I tried to fix a bug with developer tool, and It was solved when `box-sizing` property of real body field is set to `content-box`. But, I'm not sure that solution I found wouldn't cause other bugs.

**Comment by jhaemin** [comment]
@LiteHell It's a weird bug. Currently I couldn't find any solution other than your suggestion. And it seems there will be no side effects from changing to `content-box`.

If you don't mind, could you please make a pull request for this? I want you to be in the contributors list. If you mind, just let me know and I'll fix the problem by myself.

**Comment by LiteHell** [comment]
Thanks for response, I'll make a pull request as soon as possible.

**Comment by LiteHell** [comment]
I made a PR for this, see https://github.com/payw-org/eodiro/pull/276.
