### ISSUE TITLE
The inconvenience of use when changing password. (Chrome)

### ISSUE THREAD

**Issue by ddongule** [payw-org/eodiro#339]
When typing password, it focuses out so frequently.
- Only in Chrome.

preview)
![Apr-02-2021 22-32-52](https://user-images.githubusercontent.com/26598561/113419967-72658280-9403-11eb-88f6-65b7a7b1f767.gif)

**Comment by jhaemin** [comment]
Fixed by 6e04079e2aba95d725cc14c04fe772333b5ab32c.
Thanks for reporting.
